name: Tests
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: clojure:temurin-19-tools-deps-1.11.1.1208-alpine

    steps:
    - uses: actions/checkout@v2

    - name: Cache Clojure deps
      uses: actions/cache@v1
      with:
        path: /root/.m2
        key: v1-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          v1-deps-
          v1-deps-${{ hashFiles('deps.edn') }}

    - name: Install dependencies
      run: clojure -X:deps prep

    - name: Run tests
      run: clojure -M:test  2>&1
